version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_controller.yaml
    flatten: true
    vars:
      NESTED_MODULES: api
      API_DIRS: '{{.ROOT_DIR}}/api/v1alpha1/...'
      MANIFEST_OUT: '{{.ROOT_DIR}}/api/crds/manifests'
      CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/api/... {{.ROOT_DIR}}/internal/...'
      COMPONENTS: 'quota-operator'
      CHART_COMPONENTS: "[]"
      CRDS_COMPONENTS: "quota-operator"
      CRDS_PATH: '{{.ROOT_DIR}}/api/crds/manifests'
      REPO_URL: 'https://github.com/openmcp-project/quota-operator'

tasks:
  platformservice:
    desc: "  Generates a PlatformService manifest for the current version. Set the VERBOSITY env var to overwrite the default verbosity level (INFO)."
    requires:
      vars:
      - VERSION
    vars:
      VERBOSITY:
        sh: echo "${VERBOSITY:-INFO}"
    cmds:
    - cmd: |
        cat << EOF
        apiVersion: openmcp.cloud/v1alpha1
        kind: PlatformService
        metadata:
          name: quota
        spec:
          image: ghcr.io/openmcp-project/images/quota-operator:{{.VERSION}}
          verbosity: {{.VERBOSITY}}
        EOF
      silent: true
