{{- if .Values.cluster }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quota-operator.fullname" . }}-cluster
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "quota-operator.labels" $ | nindent 4 }}
data:
  {{- range $k, $v := .Values.cluster }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
