apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quota-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quota-operator.labels" . | nindent 4 }}
